name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # NOTE: compilation is done as part of the "prepare" script, which is run during npm ci
      - name: Checkout/install/compile
        uses: adamhamlin/checkout-node-project@v1

      - name: Lint
        run: npm run check

      - name: Tests
        run: npm test
